### ISSUE TITLE
an array of cells is only showing the first one

### ISSUE THREAD

**Issue by mattvenn** [TinyTapeout/tinytapeout_gds_viewer#12]
https://gds-viewer.tinytapeout.com/?model=https://mattvenn.github.io/tt08-analog-r2r-dac-3v3/tinytapeout.gds.gltf

shows only one dac_drive cell

![image](https://github.com/TinyTapeout/tinytapeout_gds_viewer/assets/634220/c80ced3b-cd8f-4d04-b1f8-818ec750a586)

but there are 8

![image](https://github.com/TinyTapeout/tinytapeout_gds_viewer/assets/634220/2ee262f6-6d24-4d68-b5a0-4122d6ecb178)

**Comment by urish** [comment]
It's actually an issue in GDS2glTF: mbalestrini/GDS2glTF#4

Once the upstream issue is fixed, the 3d viewer will render the arrays.
