### ISSUE TITLE
clicking highlights layers that are not shown

### ISSUE THREAD

**Issue by nmz787-intel** [TinyTapeout/tinytapeout_gds_viewer#2]
showing poly as red:
![image](https://github.com/TinyTapeout/tinytapeout_gds_viewer/assets/102060486/e7f6b6d8-8c92-4dc0-912b-380645737295)

disabling poly:
![image](https://github.com/TinyTapeout/tinytapeout_gds_viewer/assets/102060486/7da5b201-9ac3-45d2-a3bd-970a8f04db56)

clicking area where poly would be (but isn't currently):
![image](https://github.com/TinyTapeout/tinytapeout_gds_viewer/assets/102060486/36281f55-2fe3-41ff-b24c-397362ae334b)

left and right clicking both cause this highlighting of unshown layers.

**Comment by nmz787-intel** [comment]
technically I don't think my last screenshot shows poly selected... but the idea holds... there's some unshown layer that's getting the signal to "highlight"

**Comment by urish** [comment]
Can you please check if this still happens with the new viewer version released today?

**Comment by nmz787-intel** [comment]
@urish looks good now!
